### ISSUE TITLE
Rspec not being installed properly/not running tests

### ISSUE THREAD

**Issue by Skyd3v** [imZephox/blocipedia#2]
Hello John,

I am facing an issue as want to do this project over in TDD.When wanting to create a spec to run and while trying to write test code I am receiving the following error 👍 

Web Console is activated in the test environment, which is
usually a mistake. To ensure it's only activated in development
mode, move it to the development group of your Gemfile:

    gem 'web-console', group: :development

If you still want to run it the test environment (and know
what you are doing), put this in your Rails application
configuration:

    config.web_console.development_only = false

Any ideas how to sort this out?Thanks in advance

**Comment by Skyd3v** [comment]
I have commited the changes so you can check yourself as well.

**Comment by johnksawers** [comment]
From reading then error message, it points me towards your Gemfile.
Looking in there I can see that `web-console` is in the block for `:development,:test`
Just move that line up into the block above it that's jut for `:development`
